key={
wx.WXK_SPACE: 'Backspace', 
wx.WXK_TAB: 'Tab',
wx.WXK_RETURN: 'Enter',
wx.WXK_ESCAPE: 'Esc',
wx.WXK_DELETE: 'Delete',
wx.WXK_START: 'Start',
wx.WXK_LBUTTON: 'Left
wx.WXK_RBUTTON: 'Right
wx.WXK_CANCEL: 'Cancel',
wx.WXK_MBUTTON: 'Middle
wx.WXK_CLEAR: 'Clear',
wx.WXK_SHIFT: 'Shift',
wx.WXK_CONTROL: 'Control',
wx.WXK_MENU: 'Menu',
wx.WXK_PAUSE: 'Pause',
wx.WXK_CAPITAL: 'Capital',
wx.WXK_PRIOR: 'Page
wx.WXK_NEXT: 'Page
wx.WXK_END: 'End',
wx.WXK_HOME: 'Home',
wx.WXK_LEFT: 'Left',
wx.WXK_UP: 'Up',
wx.WXK_RIGHT: 'Right',
wx.WXK_DOWN: 'Down',
wx.WXK_SELECT: 'Select',
wx.WXK_PRINT: 'Print',
wx.WXK_EXECUTE: 'Execute',
wx.WXK_SNAPSHOT: 'Snapshot',
wx.WXK_INSERT: 'Insert',
wx.WXK_HELP: 'Help',
wx.WXK_NUMPAD0: 'Numpad0
wx.WXK_NUMPAD1: 'Numpad1
wx.WXK_NUMPAD2: 'Numpad2
wx.WXK_NUMPAD3: 'Numpad3
wx.WXK_NUMPAD4: 'Numpad4
wx.WXK_NUMPAD5: 'Numpad5
wx.WXK_NUMPAD6: 'Numpad6
wx.WXK_NUMPAD7: 'Numpad7
wx.WXK_NUMPAD8: 'Numpad8
wx.WXK_NUMPAD9: 'Numpad9
wx.WXK_MULTIPLY: 'Multiply',
wx.WXK_ADD: 'Add',
wx.WXK_SEPARATOR: 'Separator',
wx.WXK_SUBTRACT: 'Subtract',
wx.WXK_DECIMAL: 'Decimal',
wx.WXK_DIVIDE: 'Divide',
wx.WXK_F1: 'F1',
wx.WXK_F2: 'F2',
wx.WXK_F3: 'F3',
wx.WXK_F4: 'F4',
wx.WXK_F5: 'F5',
wx.WXK_F6: 'F6',
wx.WXK_F7: 'F7',
wx.WXK_F8: 'F8',
wx.WXK_F9: 'F9',
wx.WXK_F10: 'F10',
wx.WXK_F11: 'F11',
wx.WXK_F12: 'F12',
wx.WXK_F13: 'F13',
wx.WXK_F14: 'F14',
wx.WXK_F15: 'F15',
wx.WXK_F16: 'F16',
wx.WXK_F17: 'F17',
wx.WXK_F18: 'F18',
wx.WXK_F19: 'F19',
wx.WXK_F20: 'F20',
wx.WXK_F21: 'F21',
wx.WXK_F22: 'F22',
wx.WXK_F23: 'F23',
wx.WXK_F24: 'F24',
wx.WXK_NUMLOCK: 'Num
wx.WXK_SCROLL: 'Scroll
}
